name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install modules
        run: pnpm install
      
      - name: Build
        run: pnpm run build

      - name: Set Actions Allow Unsecure Commands
        run: |
           echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.TEST.c }}
          BRANCH: master
          FOLDER: /dist
          REPOSITORY_NAME: Shamaralyy/contract-frontend.github.ioo
          TARGET_FOLDER: ticktack # 打包的文件将放到静态服务器 github-actions-demo 目录下
